"""recreate_questions_table

Revision ID: 4356e1928b54
Revises: 4dace878ca55
Create Date: 2026-06-09 05:48:55.047960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4356e1928b54'
down_revision: Union[str, Sequence[str], None] = '4dace878ca55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('certification', sa.String(length=100), nullable=False),
    sa.Column('chapter', sa.String(length=50), nullable=False),
    sa.Column('section', sa.String(length=50), nullable=False),
    sa.Column('learning_objective', sa.String(length=100), nullable=False),
    sa.Column('k_level', sa.String(length=10), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('tipo_pregunta', sa.String(length=50), nullable=False),
    sa.Column('respuestas_correctas', sa.JSON(), nullable=False),
    sa.Column('translations', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_certification'), 'questions', ['certification'], unique=False)
    op.create_index(op.f('ix_questions_chapter'), 'questions', ['chapter'], unique=False)
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_index(op.f('ix_questions_learning_objective'), 'questions', ['learning_objective'], unique=False)
    op.add_column('user_answers', sa.Column('selected_option_ids', sa.JSON(), nullable=False))
    op.drop_column('user_answers', 'selected_option_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_answers', sa.Column('selected_option_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('user_answers', 'selected_option_ids')
    op.drop_index(op.f('ix_questions_learning_objective'), table_name='questions')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_chapter'), table_name='questions')
    op.drop_index(op.f('ix_questions_certification'), table_name='questions')
    op.drop_table('questions')
    # ### end Alembic commands ###
