"""add fingerprint to questions

Revision ID: caaadb5f501a
Revises: 14dfe78d5fd5
Create Date: 2026-06-15 16:15:48.459340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caaadb5f501a'
down_revision: Union[str, Sequence[str], None] = '14dfe78d5fd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('fingerprint', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_questions_fingerprint'), 'questions', ['fingerprint'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questions_fingerprint'), table_name='questions')
    op.drop_column('questions', 'fingerprint')
    # ### end Alembic commands ###
